variable "vpc" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}
variable "tags" {}
variable "env" {}
variable "alb" {}
variable "rds" {}
variable "apps" {}
variable "zone_id" {}
variable "ssh_ingress_cidr" {}
